# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20151229_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='api_id',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='api_id',
        ),
        migrations.AddField(
            model_name='result',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
