# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_auto_20151229_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='log',
            field=models.CharField(default=b'', max_length=10000),
        ),
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.CharField(default=b'{}', max_length=1000),
        ),
    ]
