# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_auto_20151229_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='result',
            new_name='report',
        ),
    ]
