# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_auto_20151229_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='date',
            field=models.DateTimeField(default=b'2015-12-30 01:44:13'),
        ),
    ]
