# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0009_auto_20151230_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
