# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0011_auto_20160302_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='code',
        ),
        migrations.AddField(
            model_name='submission',
            name='package',
            field=models.FileField(default='', upload_to=b''),
            preserve_default=False,
        ),
    ]
