# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 21:11
from __future__ import unicode_literals

from django.db import migrations
import submission.models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0014_auto_20160302_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='package',
            field=submission.models.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=submission.models.submission_directory_path),
        ),
    ]
