# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 02:10
from __future__ import unicode_literals

from django.db import migrations
import submission.models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0017_submission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='avatar',
            field=submission.models.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=b'avatars'),
        ),
    ]
