# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0018_team_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=models.ImageField(default=None, upload_to=b''),
            preserve_default=False,
        ),
    ]
