# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0019_auto_20160307_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=models.ImageField(upload_to=b'avatars'),
        ),
    ]
