# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0021_auto_20160307_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=b'avatars'),
        ),
    ]
